# Generated by Django 4.0.3 on 2022-07-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=50)),
                ('museum_code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('register', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=50, null=True)),
                ('outline', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
