# Generated by Django 4.0.3 on 2022-08-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_militaryterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militaryterm',
            name='menu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='militaryterm',
            name='museum_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='militaryterm',
            name='register',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
